# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExploreSST' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ExploreSST

  target 'ExploreSST-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    
  end

  target 'ExploreSSTTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ExploreSST-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ExploreSST-tvOS

  

end
